"""empty message

Revision ID: 48f0ab714585
Revises: 
Create Date: 2025-12-09 09:51:10.164603

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '48f0ab714585'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('log_exp_readings')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_exp_readings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('counts_per_second', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('counts_per_minute', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('microsieverts_per_hour', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mode', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('log_exp_readings_pkey'))
    )
    # ### end Alembic commands ###
