"""add device_id

Revision ID: aed4ddd31677
Revises: b650a74d8579
Create Date: 2026-01-15 15:45:00.865716

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "aed4ddd31677"
down_revision = "b650a74d8579"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logexp_readings", schema=None) as batch_op:
        batch_op.add_column(sa.Column("device_id", sa.String(length=64), nullable=True))
        batch_op.alter_column(
            "mode",
            existing_type=sa.VARCHAR(length=32),
            type_=sa.String(length=10),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("logexp_readings", schema=None) as batch_op:
        batch_op.alter_column(
            "mode",
            existing_type=sa.String(length=10),
            type_=sa.VARCHAR(length=32),
            existing_nullable=False,
        )
        batch_op.drop_column("device_id")

    # ### end Alembic commands ###
